### ISSUE TITLE
redshift: Task does not call onFailure given insufficient s3 permissions

### ISSUE THREAD

**Issue by brettfd** [fleet-data/sink-jdbc#38]
Running the sink task with insufficient s3 permission logs the following error but does not call on the onFailure URL.

```
Details: 
 -----------------------------------------------
  error:  S3ServiceException:Access Denied,Status 403,Error AccessDenied,Rid 3AA090BC464ED999,ExtRid XGNgkPs1gsHzIe9l3Q4r53mHSeZsbsReBwL6A+lua2qqBxs+G+qgc619jvuZLlZnkpvjIconMJY=,CanRetry 1
  code:      8001
  context:   Listing bucket=test-bucket-01 prefix=/fleet/fleet-temp.google-analytics-source-860b0ed.eef80aab.formatted.json
  query:     2833121
  location:  s3_utility.cpp:558
  process:   padbmaster [pid=43724]
  -----------------------------------------------;
	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(ErrorResponse.java:1830)
	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(PGMessagingContext.java:822)
	at com.amazon.redshift.client.PGMessagingContext.handleMessage(PGMessagingContext.java:647)
	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(InboundMessagesPipeline.java:312)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(PGMessagingContext.java:1080)
	at com.amazon.redshift.client.PGMessagingContext.getErrorResponse(PGMessagingContext.java:1048)
	at com.amazon.redshift.client.PGClient.handleErrorsScenario3(PGClient.java:2588)
	at com.amazon.redshift.client.PGClient.handleErrors(PGClient.java:2453)
	at com.amazon.redshift.client.PGClient.handleAtomicStmtErrors(PGClient.java:1654)
	at com.amazon.redshift.client.PGClient.executeAtomicStatement(PGClient.java:1600)
	at com.amazon.redshift.dataengine.PGBatchQueryExecutor.execute(PGBatchQueryExecutor.java:261)
	at com.amazon.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.amazon.jdbc.common.SStatement.execute(Unknown Source)
	at io.f8k.jdbc.util.query.JdbcNonQuery.run(JdbcNonQuery.java:14)
	at io.f8k.fleet.sink.redshift.query.RedshiftQuery.executeQuery(RedshiftQuery.java:55)
	at io.f8k.fleet.sink.redshift.query.RedshiftQuery.executeQuery(RedshiftQuery.java:42)
	at io.f8k.fleet.sink.redshift.query.RedshiftQueryRunner.run(RedshiftQueryRunner.java:25)
	at io.f8k.fleet.sink.redshift.RedshiftSink.load(RedshiftSink.java:258)
	at io.f8k.fleet.sink.redshift.RedshiftSink.run(RedshiftSink.java:72)
	at io.fleet.Runner.runSink(Runner.java:185)
	at io.fleet.Runner.start(Runner.java:97)
Caused by: com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: S3ServiceException:Access Denied,Status 403,Error AccessDenied,Rid 3AA090BC464ED999,ExtRid XGNgkPs1gsHzIe9l3Q4r53mHSeZsbsReBwL6A+lua2qqBxs+G+qgc619jvuZLlZnkpvjIconMJY=,CanRetry 1
Details: 
 -----------------------------------------------
  error:  S3ServiceException:Access Denied,Status 403,Error AccessDenied,Rid 3AA090BC464ED999,ExtRid XGNgkPs1gsHzIe9l3Q4r53mHSeZsbsReBwL6A+lua2qqBxs+G+qgc619jvuZLlZnkpvjIconMJY=,CanRetry 1
  code:      8001
  context:   Listing bucket=test-bucket-us-east-1 prefix=/fleet/fleet-temp.google-analytics-source-860b0ed.eef80aab.formatted.json
  query:     2833121
  location:  s3_utility.cpp:558
  process:   padbmaster [pid=43724]
  -----------------------------------------------;
```

**Comment by jre247** [comment]
Looking at the logs in API I see that the task output POST request is received but the logs indicate that no other operations have occurred such as saving the output record in the database. Logs below:

`127.0.0.1 - - [11/Dec/2017:12:59:57 +0000] "POST /tasks/13/slices/20170830000000/runs/S20170830090016620/output HTTP/1.1" 200 28 "-" "User-Agent" 586
{"ts":"2017-12-11T13:00:04.700Z","level":"debug","class":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory","method":"invoke0","message":"Task Output endpoint has been hit","type":"message","module":"api","id":"96eb71a8-6ee8-4f68-93f7-dc4863d0c793","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"type":"event","event_name":"task.output.received","ts":"2017-12-11T13:00:04.704Z","class":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory","method":"invoke0","module":"api","id":"b971b3e1-b3ea-438a-8562-5dd01eb6c521","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"ts":"2017-12-11T13:00:04.705Z","level":"debug","class":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory","method":"invoke0","message":"Task output raw: {\"startTime\":\"Dec 11, 2017 7:59:57 AM\",\"endTime\":\"Dec 11, 2017 7:59:59 AM\",\"status\":\"failed\",\"recordCount\":0,\"image\":\"redshift-sink\",\"taskId\":14,\"sliceId\":20170830000000,\"incrementMax\":0,\"message\":\"Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 6A9797D6A5FC0977)\",\"output\":{\"files\":[]},\"runId\":\"S20170830090016620\",\"runCount\":0}","type":"message","module":"api","id":"1c7d86be-cdb3-4feb-9093-d91daadc464a","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"type":"event","event_name":"task.output.deserialize.begin","ts":"2017-12-11T13:00:04.706Z","class":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory","method":"invoke0","module":"api","id":"d0040263-30f1-4649-a518-423a00dabefe","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"ts":"2017-12-11T13:00:04.710Z","level":"info","class":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory","method":"invoke0","message":"Task output deserialized","type":"message","module":"api","task_id":14,"run_id":"S20170830090016620","slice_id":20170830000000,"id":"6c21de85-4860-40cf-96d8-2805d5c40596","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"ts":"2017-12-11T13:00:04.711Z","level":"debug","class":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory","method":"invoke0","message":"Task output status: failed","type":"message","module":"api","task_id":14,"run_id":"S20170830090016620","slice_id":20170830000000,"id":"18e709fd-b3a6-461b-9e35-b3695ea07030","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"type":"event","event_name":"task.output.deserialize.finish","ts":"2017-12-11T13:00:04.711Z","class":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory","method":"invoke0","module":"api","task_id":14,"run_id":"S20170830090016620","slice_id":20170830000000,"id":"9d2e3fc3-32c4-4775-8226-d535122e2b65","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"type":"event","event_name":"task.output.logFailure.begin","ts":"2017-12-11T13:00:04.712Z","class":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory","method":"invoke0","module":"api","task_id":14,"run_id":"S20170830090016620","slice_id":20170830000000,"id":"a01b82a4-6845-4668-aad6-6acd00e408d9","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"ts":"2017-12-11T13:00:04.712Z","level":"info","class":"io.f8k.api.controllers.TaskController","method":"Output","message":"Logging failed task: S20170830090016620/14/20170830000000","type":"message","module":"api","task_id":14,"run_id":"S20170830090016620","slice_id":20170830000000,"id":"4059dd60-4eb7-4a91-9a72-b014052dc34b","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"ts":"2017-12-11T13:00:04.713Z","level":"debug","class":"io.f8k.api.controllers.TaskController","method":"Output","message":"Task run count: 0","type":"message","module":"api","task_id":14,"run_id":"S20170830090016620","slice_id":20170830000000,"id":"62c9154e-e2c0-4223-a721-339609efa24a","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"type":"event","event_name":"task.output.logFailure.finish","ts":"2017-12-11T13:00:04.713Z","class":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory","method":"invoke0","module":"api","task_id":14,"run_id":"S20170830090016620","slice_id":20170830000000,"id":"0439b72a-efca-4b12-9a99-963f9e814fb4","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"type":"event","event_name":"task.output.set.begin","ts":"2017-12-11T13:00:04.714Z","class":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory","method":"invoke0","module":"api","task_id":14,"run_id":"S20170830090016620","slice_id":20170830000000,"id":"aec8d95b-a7b7-4858-b2f0-23974cb9695d","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"ts":"2017-12-11T13:00:04.784Z","level":"trace","class":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory","method":"executeQuery","message":"method_begin","type":"method_begin","module":"api","task_id":14,"run_id":"S20170830090016620","slice_id":20170830000000,"id":"62bfd209-bf50-43fa-b8f5-9c319cb0506a","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"ts":"2017-12-11T13:00:04.846Z","level":"trace","class":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory","method":"executeQuery","message":"method_end","type":"method_end","module":"api","task_id":14,"run_id":"S20170830090016620","slice_id":20170830000000,"duration":"62 ms","id":"88c9d634-8fdf-4f4a-9c2b-2bb1f16e83fd","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"ts":"2017-12-11T13:00:04.978Z","level":"trace","class":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory","method":"executeQuery","message":"method_begin","type":"method_begin","module":"api","task_id":14,"run_id":"S20170830090016620","slice_id":20170830000000,"id":"acb6a26e-ab2d-4bf1-9938-1238458c7a8c","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"ts":"2017-12-11T13:00:05.035Z","level":"trace","class":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory","method":"executeQuery","message":"method_end","type":"method_end","module":"api","task_id":14,"run_id":"S20170830090016620","slice_id":20170830000000,"duration":"56 ms","id":"53b626e0-c286-47c9-be13-324a7440ddf4","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"ts":"2017-12-11T13:00:05.115Z","level":"trace","class":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory","method":"executeUpdate","message":"method_begin","type":"method_begin","module":"api","task_id":14,"run_id":"S20170830090016620","slice_id":20170830000000,"id":"78dbddcb-15aa-46cf-8744-910fe79349c3","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"ts":"2017-12-11T13:00:05.169Z","level":"trace","class":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory","method":"executeUpdate","message":"method_end","type":"method_end","module":"api","task_id":14,"run_id":"S20170830090016620","slice_id":20170830000000,"duration":"53 ms","id":"416192cb-e222-4d64-8f75-728663a11e05","host":"jasons-MacBook-Pro.local/10.0.0.132"}
{"type":"event","event_name":"task.output.set.finish","ts":"2017-12-11T13:00:05.240Z","class":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory","method":"invoke0","module":"api","id":"552e8b7b-1231-48ad-84be-cccbca3ed165","host":"jasons-MacBook-Pro.local/10.0.0.132"}
127.0.0.1 - - [11/Dec/2017:13:00:05 +0000] "POST /tasks/14/slices/20170830000000/runs/S20170830090016620/output HTTP/1.1" 200 28 "-" "User-Agent" 549`

**Comment by jre247** [comment]
@brettgriffin Are we sure this is still an issue? I wasn't able to reproduce this locally so perhaps code updates I had made last week happened to address this? Let me know if you can reproduce this still and if so I'll keep looking into a fix for it. Thanks.

**Comment by brettfd** [comment]
Just tested this and the task correctly POSTs to the API.
